version: '2'

services:
  app:
        user: application
        build:
          context: .
          dockerfile: Dockerfile
        tty: true
        environment:
            - PHP_DEBUGGER=xdebug
            - PHP_IDE_CONFIG=serverName=vimeo-mill-test
            - XDEBUG_CONFIG=idekey=PHPSTORM
            - XDEBUG_REMOTE_AUTOSTART=1
            - XDEBUG_REMOTE_CONNECT_BACK=1
            - XDEBUG_REMOTE_HOST=172.17.0.1
            - XDEBUG_PROFILER_ENABLE=0
            - PHP_TIMEZONE=UTC
            - WEB_DOCUMENT_ROOT=/app
        ports:
            - "1080:80"
            - "10443:443"
        volumes:
            - .:/app
